---
  - name: Collecting Pre Patching Details
    shell: |
        UPTIM=`uptime | sed 's/.*up \([^,]*\), .*/\1/'`
        echo "UPTIM"
    register: host_uptime
 
    shell: |
        LAST_REBOOT=`who -b | awk '{print $3,$4}'`
        echo "LAST_REBOOT"
    register: last_boot_time	

    shell: |
        IPADDR=`ip -4 addr | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v 127.0.0.1 | sed -e :a -e '{N; s/\n/, /g; ta}'`
        echo "IPADDR"
    register: host_IP_Addr

    shell: |
        AVA_KERNEL=`rpm -q --last kernel | wc -l`
        echo "AVA_KERNEL"
    register: ava_kernel

    shell: |
        OS_REL=`grep release /etc/redhat-release`
        echo "OS_REL"
    register: OS_Release
    no_log: true
