--- 
- name: Reboot the System if Reboot_Required for Kernel Update
  reboot:
    msg: "Reboot Initiated by Ansible for Kernel Updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  register: reboot_status
  when: reboot_needed == "Yes"